### ISSUE TITLE
Main column too narrow

### ISSUE THREAD

**Issue by bep** [gohugoio/gohugoioTheme#15]
![image](https://cloud.githubusercontent.com/assets/394382/25544804/72735454-2c5c-11e7-93dd-91da225c1452.png)

In the example above, there is nothing in the right column, yet I have to scroll to read the CLI help.

**Comment by budparr** [comment]
That's a little bit sticky because the width of the column has a direct relationship to the size of body copy, where around 75ish characters in a line is very readable. To make the column wider has the knock effect of making the type size necessarily larger.

One thing I've worked on is having the code blocks be wider than the body copy. I'll play around with both. Thanks for bringing it up.

**Comment by bep** [comment]
If 

1) the right column is mainly for the TOC 
2) the code samples are mainly coming below the TOC, what about making the code frame stick out to the right a little?

**Comment by budparr** [comment]
> the code samples are mainly coming below the TOC, what about making the code frame stick out to the right a little?

Agree. I had an example of this in my first iteration (that I had done for the news site), and will revive that code.

**Comment by budparr** [comment]
I added a script to check if the width of the block's contents are wider than the container. If so, on hover (for the moment) expand the code block. I will refine the actual behavior, but this, I think, is in the right direction.

**Comment by jmooring** [comment]
The width was slightly increased with https://github.com/gohugoio/gohugoioTheme/pull/271.

The expanding code blocks were removed a while ago with https://github.com/gohugoio/gohugoioTheme/pull/261 in favor of `overflow: auto`.
