### ISSUE TITLE
See if HLJS can work on generic (non-language specific) code blocks

### ISSUE THREAD

**Issue by budparr** [gohugoio/gohugoioTheme#16]
Currently HLJS is cued off of the class `language-html` or other appropriate language. Code blocks only get that class if they're wrapped in a short-code, and handling of the shortcode is inconsistent through the docs, leaving many left without highlight. 

So either we need to find a way to apply hljs to generic code that doesn't have that class or apply the shortcode uniformly to the code.

cc @digitalcraftsman @rdwatters

https://github.com/budparr/gohugo-theme/issues/13#issuecomment-298175677

Initially made this issue in the wrong repo. Sorry!

**Comment by budparr** [comment]
Ryan said:

> The language declaration doesn't require the shortcode. Hugo (Blackfriday) can take care of triple back ticks, which is all HLJS should need. If it's inconsistent, it just means I missed a few items :smile: The current site uses only the indented syntax (with no language declaration, if I recall), and things are still being highlighted. I'll add this to my list of cleanup this weekend; so, I'll standardize all the code blocks (some of them don't use the shortcode intentionally, since they don't benefit from a copy button, download button, or same file/file path), and also remove all the opinionated classes, IDs, etc....

**Comment by budparr** [comment]
Alright. So I may have been too aggressive with stripping out styles for things that were not Hugo. I see, too that there's Hugo stuff that is `language-html` as well `language-golang` which, the latter, I didn't account for.

**Comment by budparr** [comment]
> since they don't benefit from a copy button, download button, or same file/file path),

Yeah, that makes sense. So things that don't need those features, shouldn't be wrapped in the shortcode, therefore I need to account for them in my styling. I'll take another look. 

and, as you can see here I stripped out everything. https://github.com/budparr/gohugo-theme/blob/master/src/css/_hljs.css

But as far as I understood, HLJS is language specific, but I'll see if I can dig up something, if it's not just handled in the stylesheet.

JS:
https://github.com/budparr/gohugo-theme/blob/master/src/js/hljs.js

**Comment by budparr** [comment]
Trying to avoid this (https://hugodocs.info/templates/introduction/#2-use-to-access-the-global-context), where the HTML tags are highlighted, but not the Hugo tags (except in one case because the Hugo tag is part of the HTML:

<img width="714" alt="screen shot 2017-04-29 at 3 16 20 pm" src="https://cloud.githubusercontent.com/assets/115347/25558167/d6632984-2cee-11e7-91ac-1b233f83cc04.png">



_this is not a comment on @rdwatters work on this, but looking for cases to style around._

**Comment by rdwatters** [comment]
> Initially made this issue in the wrong repo. Sorry!

Ha, responded on my phone and didn't notice. 

I think the example you put above is a good one since I remember trying tweak a lot of the HLJS (including, for example, `hugo` as an alias for a natively supported language in HLJS) so that I could get Hugo-specific keywords. For example, I added `Site` and `Data` and a few others:

https://github.com/rdwatters/hugo-docs-concept/blob/master/themes/hugo-docs-concept/pipeline/js/scripts/highlight.pack.js#L276-L277

In retrospect, kind of a myopic move on my part since everything would break with future packages. In the hopes of saving you a step, these are the following languages I have on the current site from https://highlightjs.org/download/: 

* HTML, XML
* Go
* Markdown
* Handlebars
* Apache
* Ini (It's obnoxious that it's not the site, but the main `alias` for this is `toml`)
* CSS
* Asciidoc
* Ruby
* YAML
* Powershell
* SCSS
* JSON
* BASH
* HTTP
* JavaScript

**Comment by rdwatters** [comment]
Hmm. So I guess the HLJS "Handlebars" is a *little* better in that it recognizes the double curlies as a template variable, but it doesn't separate strings from templating logic, etc. 

Do you think we should write our own `hljs.registerLanguage` for `hugo` that we import as a module? Just copy and extend handlebars, sine it's in many ways just an extension of HTML? This is mostly me spitballing :smile:

**Comment by jmooring** [comment]
HLJS was stripped out a long time ago.
