### ISSUE TITLE
Discussion on color scheme

### ISSUE THREAD

**Issue by budparr** [gohugoio/gohugoioTheme#17]
This discussion pertains to the docs site as well as the home page/news site, because they share the same theme.

As a color scheme, I'm using the colors from the Hugo logo + a dark blue as a background (initially conceived to dampen the impact of the very bright colors given). Additionally, I'm using a light-gray background. I've favored the blue and the green for most uses, with the pink used for accents. The yellow is used only once.

<img width="492" alt="screen shot 2017-04-29 at 3 20 26 pm" src="https://cloud.githubusercontent.com/assets/115347/25558209/cf83b556-2cef-11e7-90db-230a6a48df1f.png">

As a background to this discussion, I should say that my feeling about color is that each and every use of color needs to serve a purpose and I tend to the minimal. That's a professionally derived opinion, but an opinion nonetheless. 

I use a light-gray (near white) background to reduce harsher contrasts (matters most on newer brighter screens) and to allow us to have white boxes with content that sit atop the gray (a design pattern considered effective).

Links throughout the site use the Hugo blue, with some exceptions, like where linked headlines in content boxes are green. That decision was made because the boxes already had a blue "read more" link in them, other decisions for link color were made for the sake of variety, but should be addressed for consistency.

- [x] review linked headings in boxes
- [x] review prev/next page link colors

Headings in the news section are green, therefore headings on document pages might need to be green.

- [x] review docs heading colors

Documentation menus items are blue when active (it would be too much color if non-active links were blue here). The menu's expanded section, corresponding to the page content, has a slightly darker background color to draw attention to itself as being related to the content.

<img width="982" alt="screen shot 2017-04-29 at 3 42 25 pm" src="https://cloud.githubusercontent.com/assets/115347/25558341/7a573320-2cf2-11e7-8ca0-45805f06043c.png">

Similarly page footers are a bit darker gray to signify that it's a substantial part of the page, but set off from the main page content to keep that content as clean as possible. 

- [ ]  button colors for tags are green. Review.

<img width="678" alt="screen shot 2017-04-29 at 3 41 46 pm" src="https://cloud.githubusercontent.com/assets/115347/25558338/676b3d6a-2cf2-11e7-8a69-7e6723f3ddfd.png">

- [ ] button colors for copying code blocks are blue, but turn green when a successful copy is made.

<img width="567" alt="screen shot 2017-04-29 at 3 40 41 pm" src="https://cloud.githubusercontent.com/assets/115347/25558333/4464add8-2cf2-11e7-9705-2ea1ebf33a16.png">

<img width="587" alt="screen shot 2017-04-29 at 3 40 53 pm" src="https://cloud.githubusercontent.com/assets/115347/25558332/40514b66-2cf2-11e7-8e04-5e33b2e8bf0e.png">

- [x] The "improve this page" button is not the same color as tag buttons on the news site. This was done for consistency within that section, but may be revisited.

---

- [ ] Address contrast ratios. Color contrast should be => 4.5 for the purpose of being accessible to a wide audience, and there are issues where the Hugo color scheme doesn't produce enough contrast.
- [ ] Review code blocks for color contrast. Here too some of the grays may need to be addressed.

---

It's been said that the overall effect of this color scheme is "boring." I think subtle changes, like making the body background slightly closer to white (to be measured against the white boxes) might help. Changing the color of doc page headings may help as well, and perhaps footer colors. 

Overall, I don't personally feel the site is boring, particularly because the site's purpose is for reading sometimes difficult concepts and therefore the site's color scheme is meant to reduce cognitive load, rather, for example, to exert brand. 

Naturally open for suggestion.

cc @digitalcraftsman

**Comment by rdwatters** [comment]
> each and every use of color needs to serve a purpose and I tend to the minimal.

Agreed (e.g., see [this theme](https://www.watters.io/) and [this theme](https://hugos-story.netlify.com/) that I'm tweaking and porting over to Hugo soon, hopefully). I went with loud colors for hugodocs.info because it seems like the community dug the colorfulness [based on this thread](https://discuss.gohugo.io/t/new-theme-for-hugo-docs-http-hugodocs-netlify-com/2335). Just a thought, but then again, we have veto power here :smile:

> button colors for copying code blocks are blue, but turn green when a successful copy is made. 

This is great...and the green for "copied" is a natural choice...you _could_ style the unsupported button with the Hugo red too for browsers that don't support `ExecCommand`, but that's not less common now... 

> because the site's purpose is for reading sometimes difficult concepts and therefore the site's color scheme is meant to reduce cognitive load

Agreed. It's always interesting to me how even web professionals sometimes fall prey to the idea that things need to be visually pretty and concise to be intriguing, when every bit of SEO research I've looked at shows that long blocks of (good-quality) text in black with a white background is often the best approach for content. Granted, I work in STM publishing, so I may have a skewed perception...

So my questions are as follows:

1. Are you considering putting the "download" button just to the left of the copy button?
2. We now have three admonitions for warning, tip, and note. I think the admonitions look great now. Are these your final design for all three?

**Comment by budparr** [comment]
I've not done much to the admonitions. I haven't thought much about the download button (there's an issue for it elsewhere).

It's seems with that last bit you agree with the intent, but not the substance. I'm saying I don't use black and white, and I've said elsewhere, to you, I prefer small chunks of copy. I'm not concerned here with SEO, so maybe that's what you're talking about. At any rate, no big deal. I think we're generally on the same page.

**Comment by rdwatters** [comment]
> It's seems with that last bit you agree with the intent, but not the substance. 

And the substance :smile: I can see how it seems like a few meta-references to other topics. I phrased it sloppily.

Whether it's black text on top of a white background or dark gray on top of light gray isn't an issue for me. I don't think your design is boring at all. I think your choices are substantiated and make the content easier to navigate and, therefore, understand. Some of the concepts in the docs are hard to grasp, especially for beginners, and your design is going to help.

My comment on SEO was to illustrate that often times, in my experience, content owners, business partners, and even fellow digital/marketing professionals want flashy design when they should be focusing on substantive long-form content, which has nothing to do with how it's laid out on the page as much as the total word count. And content should be written at a length proportional to the topic being discussed. As to how the content is laid out, that's up to the designer, and your rhythm is already much better than hugodocs.info, which is, admittedly, even hard for me to read sometimes when running `hugo server`. It wasn't a knock on your small-chunk-copy preferences at all :smile:  

As for the admonitions and download button, this was only curiosity. I like the former already and I'm sure the latter will look just as good as the copy button (as mentioned above).

**Comment by budparr** [comment]
we are indeed on the same page. Thanks very much for your comments.

**Comment by digitalcraftsman** [comment]
Hey Bud and Ryan,

I'm a little late to the party but should share a more detailed version of my thoughts. 

The dark blue background of the navigation combined with the Hugo logo has a good contrast (I love the contrast in the hero section of the homepage). Blue would also be the color of choice from the color palette of the Hugo logo.

However, in the docs, a combination of blue and green is used. I would rather settle down on a single primary color. Throughout is comment I'll refer the [Django](https://docs.djangoproject.com/en/1.11/intro/tutorial01/) and [Lavarel](https://laravel.com/docs/5.4/database) docs.

Both of them only use a single primary color which strengths in my eyes the identification with the Hugo color palette because the color is dominant in all areas of a page.

> I use a light-gray (near white) background to reduce harsher contrasts (matters most on newer brighter screens) and to allow us to have white boxes with content that sit atop the gray

I prefer to read text on a white background. The biggest advantage I see is the high contrast ratio between black and white. Currently, are used on list pages to link pages of a section with a headline and a summary (see screenshot of the Getting Started section above).

The single pages (in Hugo's terminology) with the actual content don't use a light-grey instead of a white background. Bud will likely have more experience with such things (i.e. light-grey vs white as background) but I would prefer a white background for the content as well due to the aforementioned black-white contrast ratio. On the one hand going fully white as in the Lavarel docs might be to much, on the other hand hand the Django docs provide a good example where a white background can be nicely combined with grey tones (for the sidebar).

@budparr could you elaborate a bit further what issue you see with newer, brighter screens? Brightness can be adjusted on most screens. But from personal experience I know that white displays aren't a good combination if you're sitting in a dark room. Hence I'm using a tool that redshifts the displayed colors in a warmer red color tone (i.e. it's redshifted). This might be the reason why many devs prefer dark color schemes. Nonetheless, hence I would go the middle-way as in the Django docs.

> Headings in the news section are green, therefore headings on document pages might need to be green.
> [ ] review docs heading colors

I would like to see them in the same color as well. As I said I would stick with a single primary color that is only used here as well, e.g. blue.

> button colors for copying code blocks are blue, but turn green when a successful copy is made.

I like the code blocks in the Django docs very much with the colored header that contains the file name and the copy button

![code](https://cloud.githubusercontent.com/assets/7010165/25654597/01b84e10-2ff2-11e7-90f4-237898e55b4b.png)

To stick to a single primary color I wouldn't highlight a successful copy of the code by changing the copy button color. Instead you would just let a small "copied" notice pop up right next to the copy button (as in the Django docs).

This changes might seem small in some spots but effect the general visual appearance in a greater way.

Last but not least I would like to request feedback from you.

**Comment by budparr** [comment]
Hey, @digitalcraftsman some notes:

> a single primary color which strengths in my eyes the identification with the Hugo color palette because the color is dominant in all areas of a page.

I've done this now. Was already in my notes todo above.

> I prefer to read text on a white background. The biggest advantage I see is the high contrast ratio between black and white.

Yeah, the near-white we use on single-page layouts as well as list-page layouts is quite close to white and the contrast ratio is 7.01 which is right on. Using the near white as opposed to white allows us to use white boxes on an overlay where needed and softens the colors atop it. I mentioned this above, but If I led you astray saying that near white was light-gray, my apologies for not being more specific in my terms.

> could you elaborate a bit further what issue you see with newer, brighter screens? Brightness can be adjusted on most screens.

On macbook pros as well as many new phones the screen is quite bright and I find that softening the colors (as mentioned above) makes them slightly less harsh on those screens. I wouldn't count on a user dimming or changing their screen.

> I like the code blocks in the Django docs very much with the colored header that contains the file name and the copy button

I very much agree with you there. Stay tuned for changes there.

Thanks very much for your comments. I think we're on the same page.

**Comment by digitalcraftsman** [comment]
> Yeah, the near-white we use on single-page layouts as well as list-page layouts is quite close to white and the contrast ratio is 7.01 which is right on. Using the near white as opposed to white allows us to use white boxes on an overlay where needed and softens the colors atop it. 

Then it makes sense sense to go fully white.

> On macbook pros as well as many new phones the screen is quite bright and I find that softening the colors (as mentioned above) makes them slightly less harsh on those screens. I wouldn't count on a user dimming or changing their screen.

The settings on each display are different but I've to agree that it's easier to soften the color than to adjust the contrast / colors of the display for a single website.

> Thanks very much for your comments. I think we're on the same page.

Thanks for the update; I'm curious what's coming next.

**Comment by budparr** [comment]
@digitalcraftsman - What do you mean when you say "Then it makes sense sense to go fully white?"

**Comment by digitalcraftsman** [comment]
I'm sorry; I forgot that I began to edit this sentence. It was actually meant that "it makes sense to not go fully white"
