### ISSUE TITLE
Add an anchor next to each heading

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/gohugoioTheme#62]
This makes it easier to point to a certain paragraph when linking a page. Currently, this is only the case for level 1 and level 2 headings.

**Comment by rdwatters** [comment]
Sorry @digitalcraftsman, but are you talking about headings/subheadings, headlines, or headers? 

If these are the in-page anchors for headings/subheadings, are you thinking to do this on the client via JS or in the templating?

**Comment by digitalcraftsman** [comment]
More precisely, I was talking about <h1> and <h2> headings.

**Comment by bep** [comment]
Could you point to a example site in the wild who benefits from this?

**Comment by budparr** [comment]
These have been in place since day-one. In fact, because I'm not big on hiding things I put the icon to the right of the heading. See the image. The anchor shows up on h2 only (h1 are page headings and thus have the URL in the address bar, though we could make the title linkable).

<img width="683" alt="screen shot 2017-07-31 at 9 36 42 am" src="https://user-images.githubusercontent.com/115347/28780179-d7ab1d8c-75d3-11e7-855e-981c4d252e0c.png">

**Comment by rdwatters** [comment]
Ah, that's where I got confused. Yes, I standardized all body copy to:

```
# => Not used in body copy
## => Heading
### => Subheading
#### => Sub-subheading
```
That's also because the previous version had headings and subheadings in the TOC, which definitely made for some long TOCs :smile:

@digitalcraftsman Did you want to add these to h3's as well then? Agreed that an h1 doesn't need this for obvious reasons...

**Comment by digitalcraftsman** [comment]
> Did you want to add these to h3's as well then?

Adding an anchor to h3's should be fine-grained enough to link stuff.
